@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam nodesep 45
skinparam ranksep 55
' Abstract Factory - persistenza (NFR-01): factory intercambiabili a runtime
abstract class "DAOFactory" as DF {
  + getUtenteDAO() : UtenteDAO
  + getProdottoDAO() : ProdottoDAO
  + getRicettaDAO() : RicettaDAO
  + getOrdineDAO() : OrdineDAO
  + getBuonoDAO() : BuonoDAO
}

class "OrdinaProdottoController" as CTL <<control>>
CTL ..> DF : <<use>> \n get*DAO()


class "DemoDAOFactory" as DemoF
class "FSDAOFactory" as FSF
class "JDBCDAOFactory" as JDBCF
DemoF -up-|> DF
FSF -up-|> DF
JDBCF -up-|> DF

interface "UtenteDAO"
interface "ProdottoDAO"
interface "RicettaDAO"
interface "OrdineDAO"
interface "BuonoDAO"

' ciascuna concrete factory crea i prodotti concreti della propria famiglia
DemoF ..> "DemoUtenteDAO"
DemoF ..> "DemoProdottoDAO"
DemoF ..> "DemoRicettaDAO"
DemoF ..> "DemoOrdineDAO"
DemoF ..> "DemoBuonoDAO"

FSF ..> "FSUtenteDAO"
FSF ..> "FSProdottoDAO"
FSF ..> "FSRicettaDAO"
FSF ..> "FSOrdineDAO"
FSF ..> "FSBuonoDAO"

JDBCF ..> "JDBCUtenteDAO"
JDBCF ..> "JDBCProdottoDAO"
JDBCF ..> "JDBCRicettaDAO"
JDBCF ..> "JDBCOrdineDAO"
JDBCF ..> "JDBCBuonoDAO"

' realizzazione dei prodotti astratti
DemoUtenteDAO .up.|> UtenteDAO
FSUtenteDAO .up.|> UtenteDAO
JDBCUtenteDAO .up.|> UtenteDAO
DemoProdottoDAO .up.|> ProdottoDAO
FSProdottoDAO .up.|> ProdottoDAO
JDBCProdottoDAO .up.|> ProdottoDAO
DemoRicettaDAO .up.|> RicettaDAO
FSRicettaDAO .up.|> RicettaDAO
JDBCRicettaDAO .up.|> RicettaDAO
DemoOrdineDAO .up.|> OrdineDAO
FSOrdineDAO .up.|> OrdineDAO
JDBCOrdineDAO .up.|> OrdineDAO
DemoBuonoDAO .up.|> BuonoDAO
FSBuonoDAO .up.|> BuonoDAO
JDBCBuonoDAO .up.|> BuonoDAO

@enduml
