@startuml
skinparam style strictuml
state "CREATED" as CRE
state "CONFIRMED" as CON
state "IN_DELIVERY" as IND
state "DELIVERED" as DEL
state "ANNULLED" as ANN
[*] --> CRE
CRE --> CON : [confirm]
CRE --> ANN : [cancel]
CON --> IND : [ship]
CON --> ANN : [cancel]
IND --> DEL : [deliver]
DEL --> [*]
ANN --> [*]
@enduml