@startuml
skinparam defaultFontSize 13
skinparam state {
  FontSize 13
  FontStyle bold
}
state "On Home" as HOME
state "On Marketplace" as MK
state "On Payment" as PAY
[*] --> HOME
HOME --> [*]

HOME --> MK : click [marketplaceBtn] / displayMarketplace()

MK --> MK : clickOrdina [scorte ok = false] / errScorte (3a)
MK --> MK : applicaBuono [codice ok && valido] / applicaSconto (4a)
MK --> PAY : clickOrdina [prodotto ok] / displayPayment()
MK --> HOME : click [homeBtn] / displayHome()

PAY --> PAY : clickPaga [campi ok && rifiutato] / errPagamento (6a)
PAY --> HOME : clickPaga [campi ok && accettato] / salva() && notifica()
PAY --> MK : clickAnnulla [ok] / reset()

@enduml